Feat/sse
AnywayClear/mokumoku-backend pull request #98
Opened 2023-08-11 02:11 UTC by flowerdonk

1. sse 연결 및 데이터 발송 로직 추가
2. 기존 Redis Pub/Sub 로직 수정(삭제)

2023-08-11 02:15 UTC, klkim1913 requested changes

2023-08-11 02:15 UTC, klkim1913 commented on src/main/java/com/anywayclear/service/DibService.java
> +        Member member = memberRepository.findByUserId(userId).orElseThrow(() -> new RuntimeException("아이디가 없습니다."));
수정해주세영

2023-08-11 02:15 UTC, klkim1913 commented on src/main/java/com/anywayclear/service/DibService.java
> +        Produce produce = produceRepository.findById(topicName).orElseThrow(() -> new RuntimeException("해당 농산물이 없습니다."));
22

2023-08-11 02:15 UTC, klkim1913 commented on src/main/java/com/anywayclear/service/RedisSubscribeService.java
>          try {
예외처리 세부화 + AOP컨트롤러 일괄처리로 바꿔주시면 좋을거같네요.

2023-08-11 02:15 UTC, klkim1913 commented on src/main/java/com/anywayclear/service/SubscribeService.java
> +        Member consumer = memberRepository.findByUserId(userId).orElseThrow(() -> new RuntimeException("아이디가 없습니다."));
.

2023-08-11 02:15 UTC, klkim1913 commented on src/main/java/com/anywayclear/service/SubscribeService.java
> +        Member seller = memberRepository.findByUserId(topicName).orElseThrow(() -> new RuntimeException("아이디가 없습니다."));
.

2023-08-13 12:30 UTC, flowerdonk commented
1. exception handler 추가
2. sse 전반적 수정
3. 구독, 찜 취소 api 및 로직 추가
4. 전반적인 불필요한 주석 삭제

2023-08-13 13:14 UTC, klkim1913 approved these changes

2023-08-13 15:50 UTC, merged